# Generated by Django 5.2.11 on 2026-02-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiranacalc', '0002_alter_calc_sno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calc',
            name='items',
            field=models.TextField(blank=True),
        ),
    ]
