# Generated by Django 5.2.11 on 2026-02-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiranacalc', '0003_alter_calc_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='calc',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
